version: '3.8'
services:
  chat-service:
    build: ./chat_service
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
      - db
    environment:
      - PYTHONUNBUFFERED=1
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: